{{- if and (eq .Values.sumologic.traces.enabled true) (eq .Values.otelagent.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sumologic.metadata.name.otelagent.daemonset" . }}
  labels:
    app: {{ template "sumologic.labels.app.otelagent.pod" . }}
    component: {{ template "sumologic.labels.app.otelagent.component" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ template "sumologic.labels.app.otelagent.pod" . }}
      component: {{ template "sumologic.labels.app.otelagent.component" . }}
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 6 }}
{{- end }}
{{- if .Values.otelagent.daemonset.podLabels }}
{{ toYaml .Values.otelagent.daemonset.podLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      annotations:
{{- if .Values.sumologic.podAnnotations }}
{{ toYaml .Values.sumologic.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.otelagent.daemonset.podAnnotations }}
{{ toYaml .Values.otelagent.daemonset.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "sumologic.labels.app.otelagent.pod" . }}
        component: {{ template "sumologic.labels.app.otelagent.component" . }}
        {{- include "sumologic.labels.common" . | nindent 8 }}
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 8 }}
{{- end }}
{{- if .Values.otelagent.daemonset.podLabels }}
{{ toYaml .Values.otelagent.daemonset.podLabels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "sumologic.metadata.name.roles.serviceaccount" . }}
      {{- if .Values.otelagent.daemonset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.otelagent.daemonset.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.otelagent.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.otelagent.daemonset.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: otelcontrib-agent
        image: {{ .Values.otelagent.daemonset.image.repository }}:{{ .Values.otelagent.daemonset.image.tag }}
        imagePullPolicy: {{ .Values.otelagent.daemonset.image.pullPolicy }}
        args:
          - "--config=/conf/traces.otelagent.conf.yaml"
        env:
        - name: GOGC
          value: "80"
{{- $ctx := .Values -}}
{{- include "kubernetes.sources.envs" (dict "Context" $ctx "Type" "traces") -}}
{{- include "kubernetes.sources.env" (dict "Context" $ctx "Type" "metrics" "Name" "default" ) | nindent 8 }}
{{- if .Values.otelagent.daemonset.extraEnvVars }}
{{- toYaml .Values.otelagent.daemonset.extraEnvVars | nindent 8 }}
{{- end }}
        resources:
          {{- toYaml .Values.otelagent.daemonset.resources | nindent 10 }}
        ports:
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 55678 # Default endpoint for Opencensus receiver.
        - containerPort: 4317  # Default endpoint for OTLP receiver.
        - containerPort: 4318  # Default endpoint for OTLP HTTP receiver.
        - containerPort: 55680 # Old endpoint for OTLP gRPC receiver.
        - containerPort: 55681 # Default endpoint for OTLP HTTP receiver. (deprecated)
        volumeMounts:
        - name: otelagent-config-vol
          mountPath: /conf
      volumes:
        - configMap:
            name: {{ template "sumologic.metadata.name.otelagent.configmap" . }}
          name: otelagent-config-vol
        - name: otelagent-vol
          persistentVolumeClaim:
            claimName: ot-efs-pvc
{{- if .Values.otelagent.daemonset.extraVolumes }}
{{- toYaml .Values.otelagent.daemonset.extraVolumes | nindent 8 }}
{{- end }}
{{- end }}
